#!/bin/bash

# Function to show an informational message
msg() {
    echo -e "\e[1;32m$*\e[0m"
}
    
# Init Make
do_make() {
    msg "Write Your Account here: Example 12345@gmail.com"
    read -e ACCOUNT
    ssh-keygen -t ed25519 -C "$ACCOUNT"
}

# Agent ssh
do_agent() {
    msg "Connect To Agent"
    eval `ssh-agent -s`
    ssh-add
}

# Grep and show ssh
do_get() {
    msg "Grep Your Ssh"
    cat ~/.ssh/id_ed25519.pub
}

# Testing connection
do_test() {
    msg "Testing Connect Ssh Github"
    ssh -T git@github.com
    msg "Yeayy Your Ssh Working Properly Now"
}

# Execute accordingly
if [[ "$1" == "--make" ]]; then
	do_make
        do_agent  
elif [[ "$1" == "--get" ]]; then
	do_get
else
	do_test
fi
