#!/usr/bin/env bash

## Kill if already running
killall -9 xfsettingsd picom polybar mpd dunst xfce4-power-manager

## xfce4-settings daemon
xfsettingsd &

## polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Wallpaper
feh --no-fehbg --bg-fill ~/.wallpaper/fox.png

## Launch Polybar
bash ~/.config/openbox/polybar/launch.sh

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Thunar Daemon
exec thunar --daemon &
